(define (problem strips-gripper-x-1)
   (:domain gripper-strips)
   (:objects rooma roomb ball1 ball2 left)
   (:init (room rooma)
          (room roomb)
          (ball ball1)
          (gripper left)
          (at-robby rooma)
          (not (at-robby roomb))
          (at ball1 rooma)
          (not (at ball2 roomb))
          (free left)
          (not (carry ball2 left))
          )
   (:goal (and
              (not (at-robby rooma))
              (at-robby roomb)
              (not (at ball2 rooma))
              (at ball2 roomb)
   )))