(define (problem strips-gripper-x-1)
   (:domain gripper-strips)
   (:objects rooma roomb ball1 ball2 left)
   (:init (room rooma)
          (room roomb)
          (ball ball1)
          (ball ball2)
          (gripper left)
          (at-robby rooma)
          (carry ball1 left)
          (at ball2 rooma)
          )
   (:goal (and
               (at ball2 roomb))))